Write-Host "WITHIN SCRIPT"
Write-Host "test_input1: @@@$($env:INPUT_TEST_INPUT1)@@@"
Write-Host "testInput2: @@@$($env:INPUT_TESTINPUT2)@@@"
Write-Host "WITHIN SCRIPT"
Write-Host "test_input1: @@@${env:INPUT_TEST_INPUT1}@@@"
Write-Host "testInput2: @@@${env:INPUT_TESTINPUT2}@@@"